# Generated by Django 3.0.5 on 2020-04-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AUTHENTICATION', '0002_auto_20200418_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Contact',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
