# Generated by Django 3.0.5 on 2020-04-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0003_auto_20200419_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
