# Generated by Django 3.0.5 on 2020-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AUTHENTICATION', '0004_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dob', models.DateField(max_length=20, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
